"""Criando tabelas iniciais

Revision ID: babd4630b1d5
Revises: 
Create Date: 2026-08-26 15:44:31.946485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'babd4630b1d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('canais_usuario',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('plataforma', sa.Enum('telegram', 'discord', name='plataforma_msg'), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('codigo_convite', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('vinculado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plataforma', 'chat_id', name='uq_plataforma_chat')
    )
    op.create_table('veiculos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.BigInteger(), nullable=False),
    sa.Column('placa', sa.String(), nullable=False),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('valor_referencia', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('mensagens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('plataforma', sa.Enum('telegram', 'discord', name='plataforma_msg'), nullable=False),
    sa.Column('canal_usuario_id', sa.BigInteger(), nullable=True),
    sa.Column('direcao', sa.String(), nullable=False),
    sa.Column('id_externo', sa.String(), nullable=True),
    sa.Column('conteudo', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('enfileirada', 'enviada', 'falha', 'respondida', name='status_msg'), nullable=False),
    sa.Column('erro_codigo', sa.String(), nullable=True),
    sa.Column('erro_descricao', sa.String(), nullable=True),
    sa.Column('payload_bruto', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('criada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('enviada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('respondida_em', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("direcao IN ('saida', 'entrada')", name='chk_direcao'),
    sa.ForeignKeyConstraint(['canal_usuario_id'], ['canais_usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordens_servico',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('veiculo_id', sa.BigInteger(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('criada_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etapas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ordem_servico_id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('notificado', sa.Boolean(), nullable=True),
    sa.Column('criada_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordens_servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etapas')
    op.drop_table('ordens_servico')
    op.drop_table('mensagens')
    op.drop_table('veiculos')
    op.drop_table('canais_usuario')
    op.drop_table('clientes')
    # ### end Alembic commands ###
